import type { Metadata } from 'next';

import { VT323 } from 'next/font/google';

import './globals.css';

const vt323 = VT323({
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${vt323.className} antialiased`}>{children}</body>
    </html>
  );
}
